kind: pipeline
name: default

steps:
## Lint Helm Charts
- name: helm-chart-tests
  image: quay.io/helmpack/chart-testing:v2.1.0
  commands:
    - ln -s $(pwd) /tmp/spring
    - ct lint --charts=/tmp/spring
    - helm template /tmp/spring > /tmp/template.yaml
    - mkdir /tmp/packages
    - helm package -d /tmp/packages /tmp/spring
