@startuml
participant "Client" as client
participant "Controller" as ctrl
participant "Service" as svc
participant "DAO" as dao

client->ctrl: get customer by id
ctrl->svc: get customer by id
svc->dao: get customer by id
alt customer exists
    svc->ctrl: return customer
    ctrl->client: 200: return customer
else customer does not exist
    svc->ctrl: return null
    ctrl->client: 200: empty response
end
@enduml